### ISSUE TITLE
Fetch Error

### ISSUE THREAD

**Issue by AurevoirXavier** [maxsam4/fork-off-substrate#2] opened 2021-03-02 05:08 UTC
```js
✗ HTTP_RPC_ENDPOINT=http://office.nkg:20000 npm start

> fork-off-substrate@1.0.0 start /home/xavier/Documents/paritytech/fork-off-substrate
> node index.js

We are intentionally using the HTTP endpoint. If you see any warnings about that, please ignore them.
2021-03-02 12:18:28        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
2021-03-02 12:18:28        API-HTTP: HTTP Provider does not have 'on' emitters, use WebSockets instead
2021-03-02 12:18:28        API-HTTP: HTTP Provider does not have 'on' emitters, use WebSockets instead
2021-03-02 12:18:28        API-HTTP: HTTP Provider does not have 'on' emitters, use WebSockets instead
2021-03-02 12:18:29        API/INIT: RPC methods not decorated: balances_usableBalance, headerMMR_genProof, staking_powerOf
Unable to resolve type Status, it will fail on construction
Unknown signed extensions CheckEthereumRelayHeaderParcel found, treating them as no-effect
Unknown types found, no types for Status
Fetching current state of the live chain. Please wait, it can take a while depending on the size of your chain.

/home/xavier/Documents/paritytech/fork-off-substrate/node_modules/node-fetch/lib/index.js:272
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at http://office.nkg:20000/ reason: Cannot create a string longer than 0x1fffffe8 characters
    at /home/xavier/Documents/paritytech/fork-off-substrate/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async HttpProvider.send (/home/xavier/Documents/paritytech/fork-off-substrate/node_modules/@polkadot/rpc-provider/http/index.js:149:20)
    at async main (/home/xavier/Documents/paritytech/fork-off-substrate/index.js:65:17) {
  type: 'invalid-json'
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fork-off-substrate@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fork-off-substrate@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/xavier/.npm/_logs/2021-03-02T04_22_46_261Z-debug.log
```

**Comment by maxsam4** [comment] 2021-03-02 08:42
Interesting. Is this on Kusama/Polkadot?

**Comment by AurevoirXavier** [comment] 2021-03-02 08:56
> Interesting. Is this on Kusama/Polkadot?

Nope, on Darwinia. I've followed the readme add binary/runtime.wasm/schema into the data folder.

**Comment by maxsam4** [comment] 2021-03-02 09:00
> Nope, on Darwinia. I've followed the readme add binary/runtime.wasm/schema into the data folder.

The problem is basically that the state size on your blockchain is now bigger (500mb+) than what the js variable can store. The solution to this problem will be to fetch state in chunks rather than in a single large query. I'll aim to push this fix on the weekend but community PRs are welcome :).

ps Can you give me access to an HTTP RPC endpoint for Darwinia? It'll allow me to test my changes.

**Comment by AurevoirXavier** [comment] 2021-03-02 09:19
> > Nope, on Darwinia. I've followed the readme add binary/runtime.wasm/schema into the data folder.
> 
> The problem is basically that the state size on your blockchain is now bigger (500mb+) than what the js variable can store. The solution to this problem will be to fetch state in chunks rather than in a single large query. I'll aim to push this fix on the weekend but community PRs are welcome :).
> 
> ps Can you give me access to an HTTP RPC endpoint for Darwinia? It'll allow me to test my changes.

What's your email? I can provide an RPC endpoint for you. Or could you use WS? There's an official WS endpoint.

**Comment by maxsam4** [comment] 2021-03-02 09:26
> What's your email? I can provide an RPC endpoint for you. Or could you use WS? There's an official WS endpoint.

My email is `hi@mudit.blog`. WS won't work since that's limited to 20 MB per request in substrate iirc.

**Comment by AurevoirXavier** [comment] 2021-03-02 09:35
> My email is `hi@mudit.blog`. WS won't work since that's limited to 20 MB per request in substrate iirc.

OMG. But my machine only got 4M upload bandwidth. Do you have to download 500mb+ data?

**Comment by maxsam4** [comment] 2021-03-02 09:39
> OMG. But my machine only got 4M upload bandwidth. Do you have to download 500mb+ data?

Lol, yes. I need to download the full state of your blockchain. Perhaps it might be best that I just make the changes and test against our blockchain and then you can test against yours on your own.

**Comment by maxsam4** [comment] 2021-03-06 10:16
@AurevoirXavier Can you please retry with the latest code?

**Comment by AurevoirXavier** [comment] 2021-03-06 10:18
> @AurevoirXavier Can you please retry with the latest code?

Sure!

**Comment by AurevoirXavier** [comment] 2021-03-06 20:15
```rust
xavier on xavier.zone in fork-off-substrate at  master <!> is ❒ v1.0.0 via ⬢ v15.11.0 takes 4s
Sun Mar  7 03:26:54 2021 - 8%
λ HTTP_RPC_ENDPOINT=http://office.nkg:20000 npm start

> fork-off-substrate@1.0.0 start
> node index.js

We are intentionally using the HTTP endpoint. If you see any warnings about that, please ignore them.
2021-03-07 03:26:56        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
2021-03-07 03:26:57        REGISTRY: Unable to resolve type Status, it will fail on construction
2021-03-07 03:26:57        REGISTRY: Unknown signed extensions CheckEthereumRelayHeaderParcel found, treating them as no-effect
2021-03-07 03:26:57        API/INIT: RPC methods not decorated: balances_usableBalance, headerMMR_genProof, staking_powerOf
2021-03-07 03:26:57        METADATA: Unknown types found, no types for Status
Fetching current state of the live chain. Please wait, it can take a while depending on the size of your chain.
 ███████████████████████████████████░░░░░ 88% | ETA: 251s | 226/256
/home/xavier/Documents/paritytech/fork-off-substrate/node_modules/node-fetch/lib/index.js:272
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at http://office.nkg:20000/ reason: Cannot create a string longer than 0x1fffffe8 characters
    at /home/xavier/Documents/paritytech/fork-off-substrate/node_modules/node-fetch/lib/index.js:272:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async HttpProvider.send (/home/xavier/Documents/paritytech/fork-off-substrate/node_modules/@polkadot/rpc-provider/http/index.js:149:20)
    at async fetchChunks (/home/xavier/Documents/paritytech/fork-off-substrate/index.js:134:19)
    at async Promise.all (index 105)
    at async fetchChunks (/home/xavier/Documents/paritytech/fork-off-substrate/index.js:149:5)
    at async main (/home/xavier/Documents/paritytech/fork-off-substrate/index.js:80:5) {
  type: 'invalid-json'
}
```

**Comment by maxsam4** [comment] 2021-03-08 04:49
@AurevoirXavier Delete `./data/storage.json` and try running `FORK_CHUNKS_LEVEL=2 HTTP_RPC_ENDPOINT=http://office.nkg:20000 npm start`. It splits the the download into even smaller chunks.

ps Do you have an Idea how large your blockchain's state is?

**Comment by AurevoirXavier** [comment] 2021-03-09 02:43
> @AurevoirXavier Delete `./data/storage.json` and try running `FORK_CHUNKS_LEVEL=2 HTTP_RPC_ENDPOINT=http://office.nkg:20000 npm start`. It splits the the download into even smaller chunks.
> 
> ps Do you have an Idea how large your blockchain's state is?

Okay, I'll try this.

How to know the size of chain state? Any tool?

**Comment by AurevoirXavier** [comment] 2021-03-09 03:43
When i set `LEVEL=2` the progress stalled. 0% ETA 0s for around 30mins

**Comment by AurevoirXavier** [comment] 2021-03-09 04:29
```rust
λ FORK_CHUNKS_LEVEL=2 HTTP_RPC_ENDPOINT=http://127.0.0.1:20000 npm start

> fork-off-substrate@1.0.0 start
> node index.js

We are intentionally using the HTTP endpoint. If you see any warnings about that, please ignore them.
2021-03-09 11:49:24        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
2021-03-09 11:49:25        REGISTRY: Unable to resolve type Status, it will fail on construction
2021-03-09 11:49:25        REGISTRY: Unknown signed extensions CheckEthereumRelayHeaderParcel found, treating them as no-effect
2021-03-09 11:49:25        API/INIT: RPC methods not decorated: balances_usableBalance, headerMMR_genProof, staking_powerOf
2021-03-09 11:49:25        METADATA: Unknown types found, no types for Status
Fetching current state of the live chain. Please wait, it can take a while depending on the size of your chain.
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 3009023s | 12/65536
/home/xavier/Downloads/fork-off-substrate/node_modules/node-fetch/lib/index.js:1461
			reject(new FetchError(`request to ${request.url} failed, reason: ${err.message}`, 'system', err));
			       ^
FetchError: request to http://127.0.0.1:20000/ failed, reason: read ECONNRESET
    at ClientRequest.<anonymous> (/home/xavier/Downloads/fork-off-substrate/node_modules/node-fetch/lib/index.js:1461:11)
    at ClientRequest.emit (node:events:378:20)
    at Socket.socketErrorListener (node:_http_client:462:9)
    at Socket.emit (node:events:378:20)
    at emitErrorNT (node:internal/streams/destroy:188:8)
    at emitErrorCloseNT (node:internal/streams/destroy:153:3)
    at processTicksAndRejections (node:internal/process/task_queues:81:21) {
  type: 'system',
  errno: 'ECONNRESET',
  code: 'ECONNRESET'
}
```

**Comment by maxsam4** [comment] 2021-03-09 04:54
@AurevoirXavier This shouldn't be happening unless your blockchain state size is hundreds of GBs. This tool can't scale to that level. I am unable to reproduce this behavior on Kusama and Polymesh. Can you please host a node of your chain on AWS or something and provide me with an HTTP RPC endpoint? I don't see any other way I can debug this.

**Comment by AurevoirXavier** [comment] 2021-03-09 06:20
> @AurevoirXavier This shouldn't be happening unless your blockchain state size is hundreds of GBs. This tool can't scale to that level. I am unable to reproduce this behavior on Kusama and Polymesh. Can you please host a node of your chain on AWS or something and provide me with an HTTP RPC endpoint? I don't see any other way I can debug this.

Okay, I'm trying to boot a new node for you.

**Comment by AurevoirXavier** [comment] 2021-03-09 06:44
Sent. Pls check email. @maxsam4

**Comment by maxsam4** [comment] 2021-03-19 09:00
@AurevoirXavier Please try again with the latest version.

**Comment by AurevoirXavier** [comment] 2021-03-19 09:02
> @AurevoirXavier Please try again with the latest version.

Sure.

I've received your email.

But always timeout.

---

And it still shows this terrible progress

```
0% | ETA: 3009023s | 12/65536
```

**Comment by maxsam4** [comment] 2021-03-19 09:05
@AurevoirXavier Don't use fork chunks
Try with `HTTP_RPC_ENDPOINT=http://127.0.0.1:20000 npm start`

If it's still timing out, you need a better node on your local server lol. I was able to use the remote node successfully.

**Comment by AurevoirXavier** [comment] 2021-03-19 09:06
> @AurevoirXavier Don't use fork chunks
> Try with `HTTP_RPC_ENDPOINT=http://127.0.0.1:20000 npm start`
> 
> If it's still timing out, you need a better node on your local server lol. I was able to use the remote node successfully.

Okay! Let me try.

**Comment by AurevoirXavier** [comment] 2021-03-20 11:59
```rust
xavier on office.nkg in fork-off-substrate at  master <!> is ❒ v1.0.0 via ⬢ v15.11.0 takes 11ms
Sat Mar 20 19:33:37 2021 - 14%
λ HTTP_RPC_ENDPOINT=http://127.0.0.1:20000 npm start

> fork-off-substrate@1.0.0 start
> node index.js

We are intentionally using the HTTP endpoint. If you see any warnings about that, please ignore them.
2021-03-20 19:33:39        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
2021-03-20 19:33:39        REGISTRY: Unable to resolve type Status, it will fail on construction
2021-03-20 19:33:39        REGISTRY: Unknown signed extensions CheckEthereumRelayHeaderParcel found, treating them as no-effect
2021-03-20 19:33:39        API/INIT: RPC methods not decorated: balances_usableBalance, headerMMR_genProof, staking_powerOf
2021-03-20 19:33:39        METADATA: Unknown types found, no types for Status
Fetching current state of the live chain. Please wait, it can take a while depending on the size of your chain.
 ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5% | ETA: 23833s | 15/256
 ```

I've a NVME SSD and i9-9900K. Why so slow? Even on local.

**Comment by maxsam4** [comment] 2021-03-20 12:24
> ```rust
> xavier on office.nkg in fork-off-substrate at  master <!> is ❒ v1.0.0 via ⬢ v15.11.0 takes 11ms
> Sat Mar 20 19:33:37 2021 - 14%
> λ HTTP_RPC_ENDPOINT=http://127.0.0.1:20000 npm start
> 
> > fork-off-substrate@1.0.0 start
> > node index.js
> 
> We are intentionally using the HTTP endpoint. If you see any warnings about that, please ignore them.
> 2021-03-20 19:33:39        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
> 2021-03-20 19:33:39        REGISTRY: Unable to resolve type Status, it will fail on construction
> 2021-03-20 19:33:39        REGISTRY: Unknown signed extensions CheckEthereumRelayHeaderParcel found, treating them as no-effect
> 2021-03-20 19:33:39        API/INIT: RPC methods not decorated: balances_usableBalance, headerMMR_genProof, staking_powerOf
> 2021-03-20 19:33:39        METADATA: Unknown types found, no types for Status
> Fetching current state of the live chain. Please wait, it can take a while depending on the size of your chain.
>  ██░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 5% | ETA: 23833s | 15/256
> ```
> 
> I've a NVME SSD and i9-9900K. Why so slow? Even on local.

Are you running this on a (slow) server?

It works fine for me locally. In any case, speed is a limitation in the node itself, not this script.

**Comment by AurevoirXavier** [comment] 2021-03-20 21:17
I running my node and this script on a NVME SSD and i9-9900K machine.

**Comment by maxsam4** [comment] 2021-03-21 05:45
Sorry but I'm unable to reproduce this "slowness". In any case, as I said, the speed here is not really dependent on the script. Your RPC node is taking too much time to process the RPC queries for some reason.

It took less than a minute to run on the external node you provided via email.

**Comment by AurevoirXavier** [comment] 2021-04-23 02:33
Don't know why. Very slow even on local NVME SSD and i9-9900K machine. 

And there's another tools https://crates.parity.io/remote_externalities/index.html It's so fast to download the chain state (on same machine)

**Comment by maxsam4** [comment] 2021-05-13 07:36
Closing this since I'm unable to reproduce the issue. Please reopen if you find any more details.

**Closed by maxsam4** 2021-05-13 07:36 UTC

**Comment by notlesh** [comment] 2021-12-15 03:27
I've been running into this same problem on Moonbeam. I'm running against a fully synced node on `localhost` that is also on a very fast machine (Ryzen 5950X, 128GB RAM, NVMe).

Specifically, I see the `Cannot create a string longer than 0x1fffffe8 characters` error (full output below) and I also see extremely long ETA times (in excess of 10 hours).

Example:

```
HTTP_RPC_ENDPOINT=http://localhost:18545 npm start -- --chain moonriver                                                                                                                                                   130 ↵

> fork-off-substrate@1.0.0 start
> node index.js "--chain" "moonriver"

We are intentionally using the HTTP endpoint. If you see any warnings about that, please ignore them.
2021-12-14 15:19:49        API/INIT: Api will be available in a limited mode since the provider does not support subscriptions
Fetching current state of the live chain. Please wait, it can take a while depending on the size of your chain.
 █████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 11% | ETA: 39075s | 29/256
/home/stephen/dev/purestake/fork-off-substrate/node_modules/node-fetch/lib/index.js:273
				return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
				                           ^
FetchError: invalid json response body at http://localhost:18545/ reason: Cannot create a string longer than 0x1fffffe8 characters
    at /home/stephen/dev/purestake/fork-off-substrate/node_modules/node-fetch/lib/index.js:273:32
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async HttpProvider._send2 (/home/stephen/dev/purestake/fork-off-substrate/node_modules/@polkadot/rpc-provider/http/index.cjs:197:18)
    at async fetchChunks (/home/stephen/dev/purestake/fork-off-substrate/index.js:195:19)
    at async fetchChunks (/home/stephen/dev/purestake/fork-off-substrate/index.js:213:7)
    at async main (/home/stephen/dev/purestake/fork-off-substrate/index.js:96:5) {
  type: 'invalid-json'
}
```

This is against our Moonriver chain, which is fairly large.

**Comment by notlesh** [comment] 2021-12-15 03:30
Lol, with `FORK_CHUNKS_LEVEL=2`:

```
0% | ETA: INFs | 1/65536
```

Edit: based on incremental progress of around 8 minutes each, this would take a little shy of one year...
